-- Roomie P2 · orders 表（规格：docs 参见 Roomie_第二阶段技术架构规格.md）
-- 写入方仅有服务端（sb_secret key，绕过 RLS）；RLS 开启且不建策略 =
-- publishable/anon key 完全不可见，防止前端误读。

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  -- 人类可读订单号（邮件/客服用），从 1001 起步
  order_number bigint generated by default as identity (start with 1001) unique,

  -- Stripe 关联
  stripe_session_id text not null unique,
  stripe_payment_intent_id text,

  -- 客户
  email text not null,
  customer_name text,
  shipping_address jsonb,

  -- 商品快照：[{handle,title,variant,qty,unit_cents}]
  items jsonb not null default '[]'::jsonb,
  amount_total integer not null,          -- 分（GST 含内）
  currency text not null default 'aud',

  -- 履约状态机：paid → shipped → delivered
  status text not null default 'paid'
    check (status in ('paid', 'shipped', 'delivered')),
  tracking_number text,
  tracking_url text,
  carrier text,

  created_at timestamptz not null default now(),
  shipped_at timestamptz,
  delivered_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists orders_email_idx on public.orders (email);
create index if not exists orders_status_idx on public.orders (status);

-- updated_at 自动维护
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists orders_updated_at on public.orders;
create trigger orders_updated_at
  before update on public.orders
  for each row execute function public.set_updated_at();

alter table public.orders enable row level security;
